### ISSUE TITLE
Make Star or Snowflake Schemas

### ISSUE THREAD

**Issue by lucasschepers** [feyclan/WT_warehouse#12]
First draft (LucidChart, can't add more things to it): https://lucid.app/lucidchart/46230668-4987-4ffe-b3bf-0016a42ecb92/edit?viewport_loc=-2010%2C-519%2C2192%2C1200%2C0_0&invitationId=inv_5a9b8e81-c9b6-44b0-855d-a59e5803f22b

First draft (Drawio): https://drive.google.com/file/d/1EekCXGpIiczcMKAFNf6TrX2wH7881r5H/view?usp=sharing

Second draft: https://drive.google.com/file/d/1SKKku20_lczpbxBe9MbJP9ZZm3raW95M/view?usp=sharing
of: https://app.diagrams.net/?libs=general;uml#G1SKKku20_lczpbxBe9MbJP9ZZm3raW95M#%7B%22pageId%22%3A%22C5RBs43oDa-KdzZeNtuy%22%7D

**Comment by feyclan** [comment]
First draft (LucidChart, can't add more things to it): https://lucid.app/lucidchart/46230668-4987-4ffe-b3bf-0016a42ecb92/edit?viewport_loc=-2010%2C-519%2C2192%2C1200%2C0_0&invitationId=inv_5a9b8e81-c9b6-44b0-855d-a59e5803f22b

First draft (Drawio):  https://drive.google.com/file/d/1EekCXGpIiczcMKAFNf6TrX2wH7881r5H/view?usp=sharing

Second draft: https://drive.google.com/file/d/1SKKku20_lczpbxBe9MbJP9ZZm3raW95M/view?usp=sharing
